import { downloadBlob, downloadTextFile } from "./api";
import { loadWindowGlobal } from "./external-scripts";
import { buildLandingHtml, type LandingData } from "./render-landing-preview";

const JSZIP_CDN = "https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js";

interface JSZipConstructor {
  new (): JSZipArchive;
}

interface JSZipArchive {
  file(path: string, data: string): void;
  generateAsync(options: { type: "blob"; compression: "DEFLATE" }): Promise<Blob>;
}

export function downloadLandingHandoff(data: LandingData, prompt: string, html: string): void {
  downloadTextFile(
    buildLandingHandoffMarkdown(data, prompt, html),
    "matters-landing-agent-handoff.md",
    "text/markdown"
  );
}

export async function downloadLandingDeployBundle(
  data: LandingData,
  prompt: string,
  html: string
): Promise<void> {
  const JSZip = await loadWindowGlobal<JSZipConstructor>(JSZIP_CDN, "JSZip");
  const zip = new JSZip();
  const slug = normalizeSlug(data.deploySlug || data.title);

  zip.file("index.html", html);
  zip.file("content.json", JSON.stringify(data, null, 2));
  zip.file("agent-handoff.md", buildLandingHandoffMarkdown(data, prompt, html));
  zip.file(
    "wrangler.toml",
    `name = "${slug}"
compatibility_date = "2026-05-05"

[assets]
directory = "."
not_found_handling = "single-page-application"
`
  );
  zip.file(
    "README.md",
    `# ${data.title.replace(/\n/g, " ")}

This bundle was generated by Matters Studio.

## Files

- \`index.html\`: standalone event landing page.
- \`content.json\`: structured page data for another agent.
- \`agent-handoff.md\`: implementation and design brief.
- \`wrangler.toml\`: Cloudflare Workers Static Assets config.

## Deploy

Use Cloudflare dashboard direct upload, or hand this folder to an agent and run:

\`\`\`bash
npx wrangler deploy
\`\`\`

Expected URL shape after deploy:

\`\`\`text
https://${slug}.workers.dev
\`\`\`
`
  );

  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
  downloadBlob(blob, `${slug}-landing-deploy.zip`);
}

export function openCloudflareDeploy(): void {
  window.open("https://dash.cloudflare.com/", "_blank", "noopener,noreferrer");
}

export function buildLandingHandoffMarkdown(
  data: LandingData,
  prompt: string,
  html = buildLandingHtml(data)
): string {
  return `# Matters Studio Activity Page Handoff

## Goal

Build, refine, or deploy this Matters activity landing page. The page should stay compatible with Matters design-system principles: restrained surfaces, clear information hierarchy, no decorative card-heavy marketing layout, and deterministic text layout over generated imagery.

## Agent Tasks

1. Review the content data and keep the first-screen promise clear.
2. Preserve modules in this order unless the event has a stronger reason: Hero, overview sections, agenda, speakers, form.
3. If editing visuals, keep the hero image text-free and preserve the left text-safe area.
4. Deploy the standalone \`index.html\` or wire the modules into an existing site.

## Hero Image Prompt

\`\`\`text
${prompt}
\`\`\`

## Content Data

\`\`\`json
${JSON.stringify(data, null, 2)}
\`\`\`

## Module Formats

- Sections: \`Title | Body\`
- Agenda: \`Time | Title | Detail\`
- Speakers: \`Name | Role | Topic\`
- Form: use \`formUrl\` as iframe source when the provider allows embedding.

## Deploy Notes

- For a quick static deploy, upload \`index.html\` to Cloudflare Pages or Workers Static Assets.
- For a repo handoff, place \`index.html\` in a public/static directory and keep \`content.json\` as the editable source.
- If the form provider blocks iframe embedding, keep the CTA link visible and add the form URL near the registration section.

## Generated HTML

\`\`\`html
${html}
\`\`\`
`;
}

function normalizeSlug(input: string): string {
  const slug = input
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/[\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return slug || "matters-landing";
}
